### ISSUE TITLE
ツアー詳細取得APIの作成

### ISSUE THREAD

**Issue by TomSuzuki** [e-harp-intern/R4FY#12]
- テーブルからツアー詳細を取得し、返す。
- レスポンス、リクエスト、エラーを考え定義する必要があります（決まったらWikiに書きます）。

## ツアー詳細に必要な情報
- リクエスト
  - ツアーID
- レスポンス
  - ツアー情報
  - 参加可否情報 → DBにテストデータを作成（seed.rb）
  - ツアー担当ガイド → DBにテストデータを作成

※テストデータは全ツアーに対して作成（ループ使えば短く書けるはず...）

**Comment by Motomae** [comment]
https://www.javadrive.jp/rails/controller/index6.html

**Comment by TomSuzuki** [comment]
最初にテストデータを追加して、DBに入っている値を眺めるとレスポンスがどのような形になるか想像しやすいと思います。
