### ISSUE TITLE
ヘルプ画面の作成

### ISSUE THREAD

**Issue by TomSuzuki** [e-harp-intern/R4FY#133]
内容はとりあえず文字で。

**Comment by TomSuzuki** [comment]
## 作成する項目
- 何をするシステムか
- どうやって使うか
  - アカウント作成の流れ
  - ツアー作成の流れ

画像無しで文章だけで説明を入れる感じにします。

**Comment by TomSuzuki** [comment]
@K-Todakun 文章の作成だけお願いします。（可能であれば言語ファイルに定義しておいていただけると助かります。）

**Comment by K-Todakun** [comment]
### とりあえずのメモです。


> 何をするシステムか

このシステムは、作成したツアーに対して管理者が、ガイドの予定と実績を考慮して、担当ガイドを調整できるものです。

> アカウント作成の流れ

アカウント作成は管理者のみが行うことができ、ガイド、管理者の両方のを作成することができます。

## ガイドのアカウント作成について
項目は3つあり、名前（必須）、メールアドレス（必須）、メモとなっています。
メールアドレスは、"@"や"."がないもの、末尾が数字で終わるものなどは登録することが出来ません。
また、すでに登録済みにメールアドレスは使用することが出来ません。ご注意ください。
メモについては必須の項目ではないので、未記入でも登録できます。
※どの項目においても作成後に、編集することが可能です。

## 管理者のアカウント作成について
項目は2つあり、名前、メールアドレスとなっています。
メールアドレスは、"@"や"."がないもの、末尾が数字で終わるものなどは登録することが出来ません。
また、すでに登録済みにメールアドレスは使用することが出来ません。ご注意ください。
※どの項目においても作成後に、編集することが可能です。

## ツアー作成の流れ
項目は10個あり、以下の通りです。
- ツアー名：ツアーの名称を入力します
- 開始日時：ツアー開始時間を入力します。
- 終了日時：ツアー終了時間を入力します。
- 大人人数：参加人数を入力します（入力は必須ではありません）。
- 子供人数：参加人数を入力します（入力は必須ではありません）。
- ガイド人数：予定人数を入力します（入力は必須ではありません）。
- 参加可否入力期限：ガイドの予定入力期限を設定します（設定しない場合は担当が決定するまで入力できます）。
- ガイドへの連絡事項：ガイドへ予定入力依頼メールを送信する際の連絡事項を入力します。
- リマインドメール：ツアー前日に担当ガイドへメールを送信するかの設定です。
- メール送信：ガイドへ予定入力依頼のメールを送信するかの設定です（開始日が過去の日時の場合は送信されません）。

大人、子供、ガイドの最大人数はそれぞれ9999人となっています。それ以上の人数は登録することが出来ません。
ツアー名、開始日時、終了日時に関しては必須の項目であり、後から変更することが出来ません。ご注意ください。
その他の項目に関しては、ツアー作成後変更することが可能です。
必要な項目のみ入力をしていただき、ツアーを作成することが出来ます。

**Comment by K-Todakun** [comment]
@TomSuzuki 
ヘルプ画面に入れる項目は、ほかに何かありますか？

**Comment by K-Todakun** [comment]
今のところ、こんな感じ
![image](https://user-images.githubusercontent.com/69948179/192698721-dd0de7b3-7cf8-48e7-aa16-9def5a379310.png)

**Comment by TomSuzuki** [comment]
良さげな気がする

**Comment by TomSuzuki** [comment]
とりあえずこれでプルリク作成をお願いします。

**Comment by K-Todakun** [comment]
プルリク作成済みです！
