### ISSUE TITLE
ツアー詳細画面でツアー状態によってテーブルの色が変わるようにする

### ISSUE THREAD

**Issue by TomSuzuki** [e-harp-intern/R4FY#136]
色定義は別ファイルのCSSで行なうこと。

**Comment by K-Todakun** [comment]
色定義はcolor.cssで行いました。
私の方で足りない色を追加しました。
もし、色の変更があればよろしくお願いいたします。
（明るすぎるとか、暗すぎるとか、、、）

**Comment by TomSuzuki** [comment]
> 色定義はcolor.cssで行いました。 私の方で足りない色を追加しました。 もし、色の変更があればよろしくお願いいたします。 （明るすぎるとか、暗すぎるとか、、、）

デザイン周りは最後にまとめてやりましょう！
