### ISSUE TITLE
ツアー作成時に途中で失敗すると中途半端なデータがDBに保存される

### ISSUE THREAD

**Issue by watashi-ha-utyujin** [e-harp-intern/R4FY#142]
ガイドスケジュールを作成に失敗したとき、ツアーの情報だけが残ってしまう

**Comment by TomSuzuki** [comment]
以下のサイトを参考に、トランザクション処理の追加をお願いします。

- [Rails トランザクションの挙動・注意点について](https://zenn.dev/neko_engineer/articles/fe8c19d5c26763)
