### ISSUE TITLE
メモに改行がある場合の動作を確認する

### ISSUE THREAD

**Issue by TomSuzuki** [e-harp-intern/R4FY#162]
改行が入っていると、jsonのフォーマットが崩れる可能性があるので、ブラウザから新しくガイドアカウントを作成し、DBに登録されたデータを確認する。

また、ガイド情報を取得する機能で改行メモが設定されたユーザーの情報を取得し、jsonフォーマットが崩れていないことを確認する。

確認が終わったら、確認内容と、レスポンスの例をこのチケットに返信してください。問題がありそうであれば、新しくバグチケットの作成をお願いします。

**Comment by watashi-ha-utyujin** [comment]
## ブラウザから新しくガイドアカウントを作成～
- ブラウザ( http://localhost:8080/accounts )からアカウントを作成。
- 作成したアカウントは名前が「#162」になっているもの。
- メモ欄に「a」のみで記載し、エンターキーによる改行を行った。
- DBのguidesを確認したところ、データの種類は「テキスト/数値」で、改行は問題なく行われていた。

## ガイド情報を取得する機能～
- Postmanで出力を確認
- ` "memo": "a\na\na" `と出力された。問題は無いと思われる

**Comment by TomSuzuki** [comment]
@watashi-ha-utyujin 問題なさそうですね。ありがとうございます！
