### ISSUE TITLE
送信したメールをDBに保存する

### ISSUE THREAD

**Issue by TomSuzuki** [e-harp-intern/R4FY#180]
必須機能ではないので、できたらで。

**Comment by chihoku1130** [comment]
内容をtext.erb側に置いてるから中身を戻すのがちょっと面倒くさそう
送信先と送信日くらいならすぐ出来そう

**Comment by TomSuzuki** [comment]
送信のコントローラーをどうにか書き換え？

**Comment by chihoku1130** [comment]
deliver_nowしてるやつ、mailメソッド？を呼び出して渡してるはずなのでここを上手く使えないかなーと思ってる
要検証

**Comment by TomSuzuki** [comment]
https://mako-wis.hatenablog.com/entry/2014/07/10/210935

そもそも本文をDB保管にするとか…？

**Comment by chihoku1130** [comment]
どの道、メールごとに中身が変わる(名前とか日程とか)から意味が無い気がした
というかトークン入った本文保存しておくのってどうなの…？という疑問も生まれてしまった…

**Comment by TomSuzuki** [comment]
トークンや初期パスワード保存は問題ありそう… タイトルだけ保存のほうがいいかな…

**Comment by chihoku1130** [comment]
送信先、紐づくツアー、送信時間（多少ずれるとは思う）、件名わかればいい気もします…

とりあえず、ちょっと気になっている方法使えるか試してほしいです↓
`logger.debug(なんかのメーラー.creation_email(hoge))`でmail(～)が出力されるのか？

**Comment by chihoku1130** [comment]
あと、送信済みメールテーブルでツアーIDがPKになってますが、アカウント作成・削除・リセット周りだと紐づかないですね
nil許容or対応考えてますか？（考えてたらごめんなさい）

**Comment by TomSuzuki** [comment]
> あと、送信済みメールテーブルでツアーIDがPKになってますが、アカウント作成・削除・リセット周りだと紐づかないですね nil許容or対応考えてますか？（考えてたらごめんなさい）

ER図だとプライマリキー設定になっていないので、DBの設定ミスですね。とりあえずバグチケット作っておきます。

**Comment by TomSuzuki** [comment]
ガイドと管理者でテーブルを分けたことにより、メール保存テーブルで管理者のメールを保存できない ＆ 仮パスワード等もメールで送信するので、この機能の実装は後回しにします。
