### ISSUE TITLE
ツアー作成後に作成したガイドにツアーの予定入力をさせるAPIを作成

### ISSUE THREAD

**Issue by TomSuzuki** [e-harp-intern/R4FY#195]
まだツアースケジュールが作成されていない場合のみ、予定入力のメールと、DBへの登録を行なう。追加済みであればエラーを返す。

`POST` `/api/v1/tours/[tour_id]/schedules/guides/[guide_id]`

仕様が複雑なので、担当者はどのように実装するかを決めた後、返信で作業予定の送信をお願いします。

**Comment by watashi-ha-utyujin** [comment]
##作業予定
:tour_id と :guide_id から guide_schedule を検索、無ければ作成。予定入力のメールを送信。tours_controllerのメール送信部分を参照。DBへの登録はメールのURLから済む？

## 質問
この機能を置いておくファイルは新規で作成でしょうか？
また、guide_scheduleを検索する際に、トークンも併せて検索・作成したほうがいいでしょうか

**Comment by TomSuzuki** [comment]
@watashi-ha-utyujin 
1. `guide_schedule` を検索後、存在しなければ作成、あればエラーを返す方針で。
1. `tours_controller` のメール送信部を関数分けして作成をお願いします。 → `common.rb` と同じ階層に新規ファイル → `include`で読み込み
1. 新規ファイル作成の方針でお願いします。
1. トークンは無いので作成しないといけないと思います。
