### ISSUE TITLE
マイアカウント画面の作成

### ISSUE THREAD

**Issue by TomSuzuki** [e-harp-intern/R4FY#264]
とりあえずログインしている管理者自身の情報を表示。

## 以下のボタンを配置
- ログアウトボタン
- パスワード変更ボタン（場所だけ）
- 自分の情報を変更

**Comment by K-Todakun** [comment]
![image](https://user-images.githubusercontent.com/69948179/190534606-0204c025-b894-4c99-95c5-a052d8262952.png)

**Comment by K-Todakun** [comment]
@TomSuzuki 
名前とメールアドレスの表示
パスワード変更ボタン作成
終わりました。
追加で何か作成するところはありますか？

なければ、pushしてプルリクエスト出します。

**Comment by TomSuzuki** [comment]
@K-Todakun ありがとうございます。
ボタンですが、下のほうにお願いします。

追加のボタンで登録情報の変更もお願いします。

**Comment by K-Todakun** [comment]
@TomSuzuki 
わかりました。

**Comment by TomSuzuki** [comment]
@K-Todakun プルリク出してから聞く感じでも大丈夫です（先にプッシュしたほうが安全かも？）。

**Comment by K-Todakun** [comment]
![image](https://user-images.githubusercontent.com/69948179/190534943-e4aa0433-db21-453f-aa36-dfed089a4ffd.png)
