### ISSUE TITLE
実施済み（実績未記入）と実績記入済みの色は逆にすべき？

### ISSUE THREAD

**Issue by TomSuzuki** [e-harp-intern/R4FY#357]
並び替えた時に何か違和感が...

![スクリーンショット 2022-09-16 102522](https://user-images.githubusercontent.com/27944833/190536574-204c65c3-e17b-4422-8d8b-404e9f7e38bc.png)

**Comment by TomSuzuki** [comment]
ついでに状態ごとの色を、色名ではなく状態名で`color.css`に定義する。（複数個所で色を変えるのが面倒なため）

**Comment by K-Todakun** [comment]
memo
1 TOUR_STATE_CODE_INCOMPLETE          未実施　黄色
2 TOUR_STATE_CODE_ASSIGNED　　　　　　未実施（担当ガイド決定）緑
4 TOUR_STATE_CODE_COMPLETE　　　　　　実施済み　青
8 TOUR_STATE_CODE_COMPLETE_RECORDED　 実施済み（実績未入力）オレンジ
256 TOUR_STATE_CODE_CANCEL　　　　　　　中止　赤

**Comment by K-Todakun** [comment]
--color-tour-state-code-○○

**Comment by K-Todakun** [comment]
--color-tour-state-code-incomplete
--color-tour-state-code-assigned
--color-tour-state-code-complete
--color-tour-state-code-complete-recorded
--color-tour-state-code-cancel
