### ISSUE TITLE
ツアー関連のデバッグ

### ISSUE THREAD

**Issue by TomSuzuki** [e-harp-intern/R4FY#372]
ブラウザからデバッグを行ないます。

### ツアー作成
- [x] 開始日時を次週、リマインド日・予定入力期限を入力しない場合にツアーの作成が完了する
- [x] 開始日を過去の日付とした場合、警告が出たうえでツアーの作成に成功する → #193
- [x] 開始日時より前の終了日時を指定した場合にツアーの作成に失敗する
- [x] ツアー名を入力しなかった場合に作成に失敗しする
- [x] メモに改行を入れた場合に正しく作成される
- [x] 人数にマイナスを指定した場合にエラーとなる

### ツアー一覧
- [x] 各種条件でのツアー検索が可能（TODO: 詳細を書く）
- [x] テーブルのソートができる

### ツアー詳細
- [x] データの取得に失敗した場合は、その表示を行なう
- [x] 各ツアー状態で正しく表示される（TODO: 表示項目条件）
- [x] 担当者が決定している場合は担当者テーブルが表示される
- [x] 参加ガイド一覧からガイド詳細へ移動できる
- [x] #408

### 担当者決定
- [x] 人数にかかわらず担当者の確定ができる
- [ ] メールを送信しない設定で正しく担当者を確定できる → #233
- [x] 実績情報が正しく表示される
- [x] テーブルのソートができる

### ツアー中止
- [x] 担当者決定前に中止すると全ガイドにメール通知が飛ぶ
- [x] 担当者決定後に中止すると担当ガイドにのみメールが飛ぶ

**Comment by K-Todakun** [comment]
バグ1：先ほど作成した、開始日時が過去の場合のalertが出た
過去でも未来でも出た。条件分岐を再度確認する必要がある。。。。。。。。。。

**Comment by K-Todakun** [comment]
> メモに改行を入れた場合に正しく作成される
改行されなかった。
![image](https://user-images.githubusercontent.com/69948179/191173386-1941403a-eb79-4ffe-84b5-f0aad4ab9f56.png)

**Comment by TomSuzuki** [comment]
> > メモに改行を入れた場合に正しく作成される
> > 改行されなかった。
> > ![image](https://user-images.githubusercontent.com/69948179/191173386-1941403a-eb79-4ffe-84b5-f0aad4ab9f56.png)

これはとりあえず仕様ということで...

**Comment by TomSuzuki** [comment]
> バグ1：先ほど作成した、開始日時が過去の場合のalertが出た 過去でも未来でも出た。条件分岐を再度確認する必要がある。。。。。。。。。。

#407

**Comment by K-Todakun** [comment]
>  各種条件でのツアー検索が可能（TODO: 詳細を書く）
ツアー名
・ツアー
・富士山
開始日時
・2022/09/15
・2022/09/15~2022/09/20
ツアー状態コード
・各ボタン単体
・全部
・2個ずつ

**Comment by K-Todakun** [comment]
@TomSuzuki 
今できる部分の確認を終わりました。

**Comment by TomSuzuki** [comment]
#233 での修正予定項目は、修正した時に確認します。
