### ISSUE TITLE
ツアー詳細編集画面の作成

### ISSUE THREAD

**Issue by TomSuzuki** [e-harp-intern/R4FY#374]
## 以下の項目を変更できるようにする
- メモ
- 開始日・終了日
- 大人人数・子供人数・ガイド人数
- リマインド日
- 予定入力期限

**Comment by K-Todakun** [comment]
@TomSuzuki 
編集項目の中に、ツアー名は入っていませんが、これで大丈夫ですか？

**Comment by TomSuzuki** [comment]
@K-Todakun ツアー名... どうしよう... とりあえずこれで...

**Comment by TomSuzuki** [comment]
余裕があればツアー名もやったほうがいいかな？

**Comment by TomSuzuki** [comment]
APIが対応しているので、ツアー名もお願いします。 @K-Todakun

**Comment by K-Todakun** [comment]
https://github.com/e-harp-intern/R4FY/wiki/tour-update
開始日時と終了日時の変更には、APIは対応していない、、、？

**Comment by K-Todakun** [comment]
@TomSuzuki 
API側を見ても、開始日時と終了日時の部分のAPIがなかったです。
API側を作成しますか？
このまま開始と終了なしでいきますか？

**Comment by TomSuzuki** [comment]
とりあえずコメントアウトで消す形でお願いします。 @K-Todakun

**Comment by K-Todakun** [comment]
わかりました。
