### ISSUE TITLE
実績をなくす

### ISSUE THREAD

**Issue by K-Todakun** [e-harp-intern/R4FY#436]
codeを削る
画面側も削る
api側も削る
画面遷移図

**Comment by TomSuzuki** [comment]
過去に担当したものはすべて出席した扱いで管理を行なう。

**Comment by TomSuzuki** [comment]
## 変更が必要なAPI機能
- 実績取得・登録系（共通パーツ変更）

## 変更が必要な画面
- ガイド詳細

**Comment by TomSuzuki** [comment]
## 担当ガイドについて
- ~~ツアーを実施済みにしたものだけ取得 or ~~過去の担当ツアー全て

**Comment by TomSuzuki** [comment]
## 削除したAPI
- ツアー実績登録

**Comment by TomSuzuki** [comment]
取得APIも合わせて変更する
