### ISSUE TITLE
【全体】日本語の修正

### ISSUE THREAD

**Issue by TomSuzuki** [e-harp-intern/R4FY#512]
## その他
- メール本文全て

## 担当ガイド決定
- `ツアー担当ガイド決定画面` → `担当ガイドの選択`

**Comment by TomSuzuki** [comment]
## 以下のメールのタイトル・文章を考える
- ツアー担当ガイド取消
- ガイド担当決定通知
- アカウント作成
- アカウント削除
- 予定入力依頼
- ツアー担当ガイドになりませんでした
- パスワード再設定
- ツアー中止

**Comment by chihoku1130** [comment]
件名：【アカウント作成】システム登録のご案内
本文：（ユーザ名）様
　　　システムへの登録が完了いたしました。
　　　ログイン情報は以下の通りです。

　　　メールアドレス：（メールアドレス）
　　　パスワード：（初期パスワード）

　　　なお、初回ログイン後はマイアカウントページ内、「パスワードの変更」からパスワードの変更をお願いいたします。

**Comment by chihoku1130** [comment]
件名：【パスワードリセット】パスワードを再設定してください
本文：（ユーザ名）様
　　　パスワードのリセットを受け付けました。
　　　下記のリンクよりパスワードの再設定を行ってください。

　　　（リンク）

**Comment by chihoku1130** [comment]
件名：【予定入力依頼】ツアー開催のご案内
本文：（ユーザ名）様
　　　ツアーの開催が決定しましたので、下記のリンクより予定の入力をお願いいたします。
　　　なお、入力期限までは同一のリンクより予定の変更が可能となっております。
　　　（リンク）

　　　開催概要は以下の通りです。
　　　ツアー名：（ツアー名）
　　　開催日：（ほげ）
　　　連絡事項：（なければこの欄表示したくないね）

　　　担当者として割当てられましたら、改めてご連絡させていただきます。

**Comment by chihoku1130** [comment]
疲れた、あとはパス

**Comment by TomSuzuki** [comment]
ツアー名のプレースホルダを削除。

**Comment by TomSuzuki** [comment]
## ツアー詳細の以下のボタン
- `担当ガイドを選択する` → `担当ガイドの選択`
- `ツアーの詳細を編集する` → `編集`
- `ツアーを実施済み状態にする` → `実施済`
- `ツアーを中止する` → `中止`

**Comment by Anne-yamaguchi** [comment]
ツアー割り当て不可だった時のメール
件名：【お知らせ】ツアー担当ガイドについて
本文：（ユーザ名）様
　　　予定のご入力をいただきありがとうございます。
　　　下記ツアーの担当ガイドとなりませんでしたので、お知らせいたします。

　　　ツアー名：
　　　開催日　：

　　　何卒よろしくお願いいたします。

**Comment by Anne-yamaguchi** [comment]
どっちでもいいとは思いますが…
メールの本文冒頭にお世話になっております。とか入れた方が印象としては良いかなと思います。

**Comment by chihoku1130** [comment]
平素は格別のご高配を賜り厚く御礼申し上げます。 
的な

**Comment by K-Todakun** [comment]
## 以下のメールのタイトル・文章を考える
- ツアー担当ガイド取消
- ガイド担当決定通知
~~- アカウント作成~~
- アカウント削除
~~- 予定入力依頼~~
~~- ツアー担当ガイドになりませんでした~~
~~- パスワード再設定~~
- ツアー中止

**Comment by TomSuzuki** [comment]
## メール

- [ ] ツアー担当ガイド取消
- [ ] ガイド担当決定通知
- [ ] アカウント作成
- [ ] アカウント削除
- [ ] 予定入力依頼~~
- [ ] ツアー担当ガイドになりませんでした
- [ ] パスワード再設定
- [ ] ツアー中止

**Comment by TomSuzuki** [comment]
メールの件名

**Comment by TomSuzuki** [comment]
続き → https://github.com/e-harp-intern/R4FY/issues/543

**Comment by chihoku1130** [comment]
細かいですけど  ~/ja.js 365行目
`管理者の作成、修正、削除`
は・で区切る方が見やすいと思います（文の句読点と混在して見える）

**Comment by Anne-yamaguchi** [comment]
細かい部分をもうひとつ追加します。
リマインドメールの当日はよろしくお願い致します。がここだけ「致します」なの気になります。
揃えて「いたします」で良いと思います。
