### ISSUE TITLE
【その他】ログアウト状態で存在しないページに行こうとするとタイムアウトする

### ISSUE THREAD

**Issue by chihoku1130** [e-harp-intern/R4FY#518]
Started GET "/e-harp" for 61.198.28.222 at 2022-09-26 06:43:04 +0000
Processing by FrontController#index as HTML
  Parameters: {"not_found"=>"e-harp"}
  Admin Load (0.1ms)  SELECT "admins".* FROM "admins" WHERE "admins"."id" IS NULL LIMIT ?  [["LIMIT", 1]]
  ↳ app/controllers/front_controller.rb:14:in `index'
Redirected to http://manage.e-harp.jp/
Completed 302 Found in 3ms (ActiveRecord: 0.1ms | Allocations: 1100)

**Comment by TomSuzuki** [comment]
Rails側の表示用のコントローラーでエラーはいてるのが原因です。（多分）

修正します。
