### ISSUE TITLE
【API】最大大人人数を決める

### ISSUE THREAD

**Issue by K-Todakun** [e-harp-intern/R4FY#520]

**Comment by K-Todakun** [comment]
子供最大人つけます、、、？

**Comment by TomSuzuki** [comment]
子供、大人、ガイドすべてで設定を追加します。

**Comment by TomSuzuki** [comment]
@K-Todakun [[Rails][validation]integerに対する最小値や最大値などの設定 - Qiita](https://qiita.com/nk1997tks18/items/8424ffc62a5231768ef6) を参考に 9999人まで設定できるようにバリデーションの追加をお願いします。
