### ISSUE TITLE
担当ガイドの設定画面（＋画面内機能）を作成する

### ISSUE THREAD

**Issue by TomSuzuki** [e-harp-intern/R4FY#65]
ツアーを担当するガイドを決定する画面を作成します。設定するべきガイドの人数はツアー詳細APIで取得可能なので、その人数を選択し、Web APIで送信する機能も作成します。参加不可と回答しているガイドは選択できないよう作成してください。

送信する情報は、Wikiの担当ガイド設定APIを参照してください。

ツアーの詳細情報が見れるページから、新しい画面を作って作業をお願いします。

**Comment by K-Todakun** [comment]
> 参加不可と回答しているガイドは選択できないよう作成してください。
>
参加不可はチェックボックスごと表示しない方向で進めてみます。

**Comment by K-Todakun** [comment]
次は、チェックボックスを選択できる個数を制御する
ダミーデータで、ガイドさんが一部参加できて、一部参加できないデータがあると、検証しやすくなる。
