### ISSUE TITLE
検証環境用設定の作成

### ISSUE THREAD

**Issue by TomSuzuki** [e-harp-intern/R4FY#7]
- Vue.js をビルドしてRailsの中に置く
- ~~CORS設定変更~~
- ~~Web API の場所を変更~~
- Rails 側にフロント表示用の設定を作成

**Comment by chihoku1130** [comment]
リマインドメールの設定周り
開発と検証簡単に切り替えられるようにしたい（.envを2個持たせる感じにする？）

**Comment by TomSuzuki** [comment]
持たせてもいいし、検証の時に書き換えるバッチファイルを用意してもいい気がする（どっちにしろ検証環境で動かすときにVue.jsをビルドするためのバッチファイルは用意する予定）

**Comment by chihoku1130** [comment]
おまかせマンモス、メール周りはもう少し綺麗にしたいと思ってる(思ってるだけ)
今更っすけど、検証環境=リリース時と同様って認識で合ってますよね？

**Comment by TomSuzuki** [comment]
Yes

**Comment by TomSuzuki** [comment]
Rails側でVue.jsの表示ができるようにする

**Comment by TomSuzuki** [comment]
メールは別チケットにします。
