### ISSUE TITLE
ガイドに予定入力メールを送信する

### ISSUE THREAD

**Issue by TomSuzuki** [e-harp-intern/R4FY#70]
ツアー作成時の機能にメールの送信を追加。一人ずつ送信する。以下のようなURLを含めること。
※テスト環境のため、URLを変更することは考えなくOKです。

`http://localhost:8080/guides/input_schedule/[生成したToken]`

**Comment by TomSuzuki** [comment]
@chihoku1130 
`/api/app/controllers/api/v1/tours_controller.rb` の `create` 内にメール送信の場所を作ってます。

**Comment by TomSuzuki** [comment]
https://railsguides.jp/action_mailer_basics.html#action-mailer%E3%81%AE%E3%83%93%E3%83%A5%E3%83%BC%E3%81%A7url%E3%82%92%E7%94%9F%E6%88%90%E3%81%99%E3%82%8B

URLの生成はこっちを使ったほうがいいのかな…？

**Comment by chihoku1130** [comment]
環境依存考えるとこの方法が良さそう

**Comment by chihoku1130** [comment]
> https://railsguides.jp/action_mailer_basics.html#action-mailer%E3%81%AE%E3%83%93%E3%83%A5%E3%83%BC%E3%81%A7url%E3%82%92%E7%94%9F%E6%88%90%E3%81%99%E3%82%8B
> 
> URLの生成はこっちを使ったほうがいいのかな…？

読んでみたけど、Rails的なページ指定でトークン周りをどうするかとか考えてなかったのでいったん従来の方法で作成
動確お願いします
