### ISSUE TITLE
トークンを使用してガイド情報・ツアー情報を取得できるようにする

### ISSUE THREAD

**Issue by TomSuzuki** [e-harp-intern/R4FY#72]
関連付けされたガイドの情報だけを取得できるようにする。

以下のようなURLをたたくと、ガイドの自分自身の情報と関連付けされたツアー情報を取得できるようにする。

`localhost:3000/api/v1/guides/[トークン]` ※トークンはDBに入っているデータを使用してください。

## 考え方
1. トークンテーブルから、トークンを用いてガイドIDを取得。
2. ガイドIDをもとにガイドテーブルからガイド情報を取得。
3. ガイド情報を返す。

※ツアーの情報も同じように取得。

## レスポンスの例
こんな感じになるはずです。

```json
{
  "status": "success",
  "data": {
    "guide": {
      "name": "xxxx以下省略" 
     },
     "tour": {
        "name": "以下省略ツアー"
     }
  }
}
```

## 参考になりそうなもの
- [joins | Railsドキュメント](https://railsdoc.com/page/joins)
- [Rails における内部結合、外部結合まとめ - Qiita](https://qiita.com/yuyasat/items/c2ad37b5a24a58ee3d30)

**Comment by watashi-ha-utyujin** [comment]
## 作業内容 
- DBからトークンを利用してガイド・ツアー情報を取得する際に、nilの場合の処理を追加しました
## 確認内容
- Postmanにて動作を確認しました
