### ISSUE TITLE
中止メールを送信する

### ISSUE THREAD

**Issue by TomSuzuki** [e-harp-intern/R4FY#74]
ツアーの中止が行われたときに、以下の条件で中止メールを送信する。ツアー中止コントローラーに追加機能として実装すること。メールの文章は条件によって変える必要はない。

## 条件
- 担当者決定前 ...担当者テーブルにある、ガイド全員（ツアーIDが同じものだけ）
- 担当者決定後 ...担当になったガイド

※担当者決定前・後はツアー状態コードを見る。ツアー状態のコードは `api/app/controllers/concerns/common.rb` で定義しているものを使用。

**Comment by watashi-ha-utyujin** [comment]
.

**Comment by watashi-ha-utyujin** [comment]
仕様の追加
- すでに中止済の場合は中止済みであることをエラーとして返す
